from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import app.views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", app.views.index, name="index"),
    path("api/students", app.views.view_students, name="students"),
    path('api/students/search', app.views.search_student, name='general_student_search'),
    path("api/students/login", app.views.login_student, name="login_student"),
    path("api/students/auth", app.views.auth_student, name="auth_student"),
    path("api/teacher/login", app.views.login_teacher, name="login_teacher"),
    path("api/teacher/auth", app.views.auth_teacher, name="authentication_teacher"),
    path("api/teacher/search", app.views.search_teacher, name="search_teacher"),
    path("api/teacher/search/turmas", app.views.get_turmas, name="get_turmas"),
    path("api/teacher/search/turma", app.views.get_turma, name="get_turma"),
    path("api/teacher/get/alunos", app.views.get_alunos_por_turma, name="get_alunos_por_turma"),
    path("api/teacher/search/disciplinas", app.views.get_disciplinas_lecionadas, name="get_disciplinas"),
    path("api/teacher/notas/get", app.views.get_notas_aluno, name="get_notas_aluno"),
    path("api/teacher/notas/salvar", app.views.salvar_notas, name="salvar_notas"),
    path("api/teacher/notas/turma/get", app.views.get_notas_turma, name="get_notas_turma"),
    path("api/teacher/notas/turma/salvar", app.views.salvar_notas_turma, name="salvar_notas_turma"),
    path("api/students/notas", app.views.get_boletim_aluno, name="get_boletim_aluno"),
    path("api/teacher/turma/disciplinas", app.views.get_disciplinas_da_turma, name="get_disciplinas_da_turma"),
    path("api/teacher/frequencia/turma/get", app.views.get_frequencia_turma, name="get_frequencia_turma"),
    path("api/teacher/frequencia/turma/salvar", app.views.salvar_frequencia_turma, name="salvar_frequencia_turma"),
    path("api/teacher/frequencia/registros", app.views.get_registros_frequencia, name="get_registros_frequencia"),
    path("api/teacher/calendario/eventos", app.views.get_eventos, name="get_eventos"),
    path("api/teacher/calendario/eventos/criar", app.views.criar_evento, name="criar_evento"),
    path("api/teacher/calendario/eventos/<int:evento_id>/deletar", app.views.deletar_evento, name="deletar_evento"),
    path("api/teacher/conteudos", app.views.get_conteudos, name="get_conteudos"),
    path("api/teacher/conteudos/criar", app.views.criar_conteudo, name="criar_conteudo"),
    path("api/teacher/conteudos/<int:conteudo_id>/deletar", app.views.deletar_conteudo, name="deletar_conteudo"),
    path("api/teacher/atividades", app.views.get_atividades, name="get_atividades"),
    path("api/teacher/atividades/criar", app.views.criar_atividade, name="criar_atividade"),
    path("api/teacher/atividades/<int:atividade_id>/deletar", app.views.deletar_atividade, name="deletar_atividade"),
    path("api/teacher/comunicados", app.views.get_comunicados, name="get_comunicados"),
    path("api/teacher/comunicados/criar", app.views.criar_comunicado, name="criar_comunicado"),
    path("api/teacher/comunicados/<int:comunicado_id>/deletar", app.views.deletar_comunicado, name="deletar_comunicado"),
    path("api/coordenacao/login", app.views.login_coordenacao, name="login_coordenacao"),
    path("api/coordenacao/auth", app.views.auth_coordenacao, name="auth_coordenacao"),
    path("api/coordenacao/professores", app.views.get_professores_coordenacao, name="get_professores_coordenacao"),
    path("api/coordenacao/professores/criar", app.views.criar_professor, name="criar_professor"),
    path("api/coordenacao/escola", app.views.get_escola_coordenador, name="get_escola_coordenador"),
    path("api/coordenacao/professores/<int:professor_id>", app.views.get_professor_detalhe, name="get_professor_detalhe"),
    path("api/coordenacao/professores/<int:professor_id>/editar", app.views.editar_professor, name="editar_professor"),
    path("api/coordenacao/opcoes-cadastro-professor", app.views.get_opcoes_cadastro_professor, name="get_opcoes_cadastro_professor"),
    path("api/coordenacao/professores/<int:professor_id>/deletar", app.views.deletar_professor, name="deletar_professor"),
    path("api/coordenacao/alunos", app.views.get_alunos_coordenacao, name="get_alunos_coordenacao"),
    path("api/coordenacao/alunos/<int:aluno_id>", app.views.get_aluno_detalhe, name="get_aluno_detalhe"),
    path("api/coordenacao/alunos/<int:aluno_id>/editar", app.views.editar_aluno, name="editar_aluno"),
    path("api/coordenacao/alunos/<int:aluno_id>/deletar", app.views.deletar_aluno, name="deletar_aluno"),
    path("api/coordenacao/alunos/criar", app.views.criar_aluno, name="criar_aluno"),
    path("api/coordenacao/opcoes-cadastro-aluno", app.views.get_opcoes_cadastro_aluno, name="get_opcoes_cadastro_aluno"),
    path("api/coordenacao/alunos/<int:aluno_id>/visao-geral", app.views.get_aluno_visao_geral, name="get_aluno_visao_geral"),
    path("api/coordenacao/alunos/<int:aluno_id>/advertencias/criar", app.views.criar_advertencia, name="criar_advertencia"),
    path("api/coordenacao/advertencias/<int:advertencia_id>/deletar", app.views.deletar_advertencia, name="deletar_advertencia"),
    path("api/coordenacao/calendario/eventos", app.views.get_eventos_coordenacao, name="get_eventos_coordenacao"),
    path('api/coordenacao/calendario/eventos/<int:evento_id>', app.views.get_evento_detalhe, name='get_evento_detalhe'),
    path("api/coordenacao/calendario/eventos/criar", app.views.criar_evento_coordenacao, name="criar_evento_coordenacao"),
    path("api/coordenacao/calendario/eventos/<int:evento_id>/editar", app.views.editar_evento_coordenacao, name="editar_evento_coordenacao"),
    path("api/coordenacao/calendario/eventos/<int:evento_id>/deletar", app.views.deletar_evento_coordenacao, name="deletar_evento_coordenacao"),
    path("api/coordenacao/professores-simples", app.views.get_lista_professores_simples, name="get_lista_professores_simples"),
    path("api/coordenacao/professores/<int:professor_id>/turmas", app.views.get_turmas_do_professor, name="get_turmas_do_professor"),
    path('api/coordenacao/comunicados', app.views.get_comunicados_coordenacao, name='get_comunicados_coordenacao'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
