from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import app.views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", app.views.index, name="index"),
    path("api/students", app.views.view_students, name="students"),
    path('api/students/search', app.views.search_student, name='general_student_search'),
    path("api/students/login", app.views.login_student, name="login_student"),
    path("api/students/auth", app.views.auth_student, name="auth_student"),
    path("api/teacher/login", app.views.login_teacher, name="login_teacher"),
    path("api/teacher/auth", app.views.auth_teacher, name="authentication_teacher"),
    path("api/teacher/search", app.views.search_teacher, name="search_teacher"),
    path("api/teacher/search/turmas", app.views.get_turmas, name="get_turmas"),
    path("api/teacher/search/turma", app.views.get_turma, name="get_turma"),
    path("api/teacher/get/alunos", app.views.get_alunos_por_turma, name="get_alunos_por_turma"),
    path("api/teacher/search/disciplinas", app.views.get_disciplinas_lecionadas, name="get_disciplinas"),
    path("api/teacher/notas/get", app.views.get_notas_aluno, name="get_notas_aluno"),
    path("api/teacher/notas/salvar", app.views.salvar_notas, name="salvar_notas"),
    path("api/teacher/notas/turma/get", app.views.get_notas_turma, name="get_notas_turma"),
    path("api/teacher/notas/turma/salvar", app.views.salvar_notas_turma, name="salvar_notas_turma"),
    path("api/students/notas", app.views.get_boletim_aluno, name="get_boletim_aluno"),
    path("api/teacher/turma/disciplinas", app.views.get_disciplinas_da_turma, name="get_disciplinas_da_turma"),
    path("api/teacher/frequencia/turma/get", app.views.get_frequencia_turma, name="get_frequencia_turma"),
    path("api/teacher/frequencia/turma/salvar", app.views.salvar_frequencia_turma, name="salvar_frequencia_turma"),
    path("api/teacher/frequencia/registros", app.views.get_registros_frequencia, name="get_registros_frequencia"),
    # path("api/teacher/calendario/eventos", app.views.get_eventos, name="get_eventos"),
    # path("api/teacher/calendario/eventos/criar", app.views.criar_evento, name="criar_evento"),
    # path("api/teacher/calendario/eventos/<int:evento_id>/deletar", app.views.deletar_evento, name="deletar_evento"),
    path('api/teacher/calendario/visualizar', app.views.get_eventos_professor_visualizacao, name='get_eventos_professor_visualizacao'),
    path("api/teacher/conteudos", app.views.get_conteudos, name="get_conteudos"),
    path("api/teacher/conteudos/criar", app.views.criar_conteudo, name="criar_conteudo"),
    path("api/teacher/conteudos/<int:conteudo_id>/deletar", app.views.deletar_conteudo, name="deletar_conteudo"),
    path("api/teacher/atividades", app.views.get_atividades, name="get_atividades"),
    path("api/teacher/atividades/criar", app.views.criar_atividade, name="criar_atividade"),
    path("api/teacher/atividades/<int:atividade_id>/deletar", app.views.deletar_atividade, name="deletar_atividade"),
    path("api/teacher/comunicados", app.views.get_comunicados, name="get_comunicados"),
    path("api/teacher/comunicados/criar", app.views.criar_comunicado, name="criar_comunicado"),
    path("api/teacher/comunicados/<int:comunicado_id>/deletar", app.views.deletar_comunicado, name="deletar_comunicado"),
    path("api/coordenacao/login", app.views.login_coordenacao, name="login_coordenacao"),
    path("api/coordenacao/auth", app.views.auth_coordenacao, name="auth_coordenacao"),
    path("api/coordenacao/professores", app.views.get_professores_coordenacao, name="get_professores_coordenacao"),
    path("api/coordenacao/professores/criar", app.views.criar_professor, name="criar_professor"),
    path("api/coordenacao/escola", app.views.get_escola_coordenador, name="get_escola_coordenador"),
    path("api/coordenacao/professores/<int:professor_id>", app.views.get_professor_detalhe, name="get_professor_detalhe"),
    path("api/coordenacao/professores/<int:professor_id>/editar", app.views.editar_professor, name="editar_professor"),
    path("api/coordenacao/opcoes-cadastro-professor", app.views.get_opcoes_cadastro_professor, name="get_opcoes_cadastro_professor"),
    path("api/coordenacao/professores/<int:professor_id>/deletar", app.views.deletar_professor, name="deletar_professor"),
    path("api/coordenacao/alunos", app.views.get_alunos_coordenacao, name="get_alunos_coordenacao"),
    path("api/coordenacao/alunos/<int:aluno_id>", app.views.get_aluno_detalhe, name="get_aluno_detalhe"),
    path("api/coordenacao/alunos/<int:aluno_id>/editar", app.views.editar_aluno, name="editar_aluno"),
    path("api/coordenacao/alunos/<int:aluno_id>/deletar", app.views.deletar_aluno, name="deletar_aluno"),
    path("api/coordenacao/alunos/criar", app.views.criar_aluno, name="criar_aluno"),
    path("api/coordenacao/opcoes-cadastro-aluno", app.views.get_opcoes_cadastro_aluno, name="get_opcoes_cadastro_aluno"),
    path("api/coordenacao/alunos/<int:aluno_id>/visao-geral", app.views.get_aluno_visao_geral, name="get_aluno_visao_geral"),
    path("api/coordenacao/alunos/<int:aluno_id>/advertencias/criar", app.views.criar_advertencia, name="criar_advertencia"),
    path("api/coordenacao/advertencias/<int:advertencia_id>/deletar", app.views.deletar_advertencia, name="deletar_advertencia"),
    path("api/coordenacao/calendario/eventos", app.views.get_eventos_coordenacao, name="get_eventos_coordenacao"),
    path('api/coordenacao/calendario/eventos/<int:evento_id>', app.views.get_evento_detalhe, name='get_evento_detalhe'),
    path("api/coordenacao/calendario/eventos/criar", app.views.criar_evento_coordenacao, name="criar_evento_coordenacao"),
    path("api/coordenacao/calendario/eventos/<int:evento_id>/editar", app.views.editar_evento_coordenacao, name="editar_evento_coordenacao"),
    path("api/coordenacao/calendario/eventos/<int:evento_id>/deletar", app.views.deletar_evento_coordenacao, name="deletar_evento_coordenacao"),
    path("api/coordenacao/professores-simples", app.views.get_lista_professores_simples, name="get_lista_professores_simples"),
    path("api/coordenacao/professores/<int:professor_id>/turmas", app.views.get_turmas_do_professor, name="get_turmas_do_professor"),
    path('api/coordenacao/comunicados', app.views.get_comunicados_coordenacao, name='get_comunicados_coordenacao'),
    path('api/coordenacao/comunicados/criar', app.views.criar_comunicado_coordenacao, name='criar_comunicado_coordenacao'),
    path('api/coordenacao/comunicados/<int:comunicado_id>', app.views.get_comunicado_detalhe, name='get_comunicado_detalhe'),
    path('api/coordenacao/comunicados/<int:comunicado_id>/editar', app.views.editar_comunicado_coordenacao, name='editar_comunicado_coordenacao'),
    path('api/coordenacao/comunicados/<int:comunicado_id>/deletar', app.views.deletar_comunicado_coordenacao, name='deletar_comunicado_coordenacao'),
    path('api/coordenacao/advertencias', app.views.get_advertencias_coordenacao, name='get_advertencias_coordenacao'),
    path('api/coordenacao/advertencias/criar', app.views.criar_advertencia_coordenacao, name='criar_advertencia_coordenacao'),
    path('api/coordenacao/advertencias/<int:advertencia_id>', app.views.get_advertencia_detalhe, name='get_advertencia_detalhe'),
    path('api/coordenacao/advertencias/<int:advertencia_id>/editar', app.views.editar_advertencia_coordenacao, name='editar_advertencia_coordenacao'),
    path('api/coordenacao/advertencias/<int:advertencia_id>/deletar', app.views.deletar_advertencia_coordenacao, name='deletar_advertencia_coordenacao'),
    path('api/coordenacao/advertencias/<int:advertencia_id>/pdf', app.views.gerar_advertencia_pdf, name='gerar_advertencia_pdf'),
    path('api/coordenacao/turmas', app.views.get_turmas_coordenacao, name='get_turmas_coordenacao'),
    path('api/coordenacao/turmas/<str:nome_turma>/horarios', app.views.get_horarios_turma, name='get_horarios_turma'),
    path('api/coordenacao/turmas/<str:nome_turma>/horarios/opcoes', app.views.get_opcoes_horario_turma, name='get_opcoes_horario_turma'),
    path('api/coordenacao/turmas/<str:nome_turma>/horarios/salvar', app.views.salvar_horario_turma, name='salvar_horario_turma'),
    path('api/coordenacao/disciplinas', app.views.get_disciplinas_coordenacao, name='get_disciplinas_coordenacao'),
    path('api/coordenacao/disciplinas/<int:disciplina_id>/renomear', app.views.renomear_disciplina_coordenacao, name='renomear_disciplina_coordenacao'),
    path('api/corrigir/disciplinas', app.views.get_disciplinas_corrigir, name='get_disciplinas_corrigir'),
    path('api/corrigir/disciplinas/criar', app.views.criar_disciplina_corrigir, name='criar_disciplina_corrigir'),
    path('api/corrigir/disciplinas/<int:disciplina_id>/renomear', app.views.renomear_disciplina, name='renomear_disciplina'),
    path('api/corrigir/disciplinas/corrigir-nome-lecionado', app.views.corrigir_nome_lecionado, name='corrigir_nome_lecionado'),
    path('api/corrigir/turmas', app.views.get_turmas_corrigir, name='get_turmas_corrigir'),
    path('api/corrigir/turmas/renomear', app.views.renomear_turma, name='renomear_turma'),
    path('api/corrigir/alunos', app.views.get_alunos_corrigir, name='get_alunos_corrigir'),
    path('api/corrigir/alunos/<int:aluno_id>/mover-turma', app.views.mover_aluno_turma, name='mover_aluno_turma'),
    path("api/blog/login", app.views.login_blogger, name="login_blogger"),
    path("api/blog/auth", app.views.auth_blogger, name="auth_blogger"),
    path("api/blog/posts", app.views.get_posts, name="get_posts"),
    path("api/blog/posts/<int:post_id>", app.views.get_post_detalhe, name="get_post_detalhe"),
    path("api/blog/posts/criar", app.views.criar_post, name="criar_post"),
    path("api/blog/posts/<int:post_id>/editar", app.views.editar_post, name="editar_post"),
    path("api/blog/posts/<int:post_id>/deletar", app.views.deletar_post, name="deletar_post"),
    path("api/teacher/avaliacoes", app.views.avaliacoes_list_create),
    path("api/teacher/avaliacoes/<int:avaliacao_id>", app.views.avaliacao_detail),
    path("api/teacher/avaliacoes/<int:avaliacao_id>/pdf", app.views.avaliacao_emitir_pdf),
    path("api/teacher/avaliacoes/questoes/<int:questao_id>/imagem", app.views.avaliacao_upload_imagem),
    path("api/teacher/opcoes-avaliacao", app.views.opcoes_avaliacao),
    path("api/coordenacao/avaliacoes", app.views.get_avaliacoes_coordenacao),
    path("api/coordenacao/avaliacoes/<int:avaliacao_id>", app.views.avaliacao_detalhe_coordenacao),
    path("api/coordenacao/avaliacoes/<int:avaliacao_id>/pdf", app.views.avaliacao_emitir_pdf_coordenacao),
    path('api/teacher/avaliacoes', app.views.get_avaliacoes_professor, name='get_avaliacoes_professor'),
    path('api/teacher/avaliacoes/criar', app.views.criar_avaliacao, name='criar_avaliacao'),
    path('api/teacher/avaliacoes/<int:avaliacao_id>/pdf', app.views.gerar_avaliacao_pdf, name='gerar_avaliacao_pdf'),
    path('api/coordenacao/mensagens', app.views.mensagens_list_create_coordenacao),
    path('api/coordenacao/mensagens/opcoes', app.views.opcoes_mensagem_coordenacao),
    path('api/coordenacao/mensagens/<int:conversa_id>', app.views.mensagem_conversa_detalhe),
    path('api/professor/mensagens', app.views.mensagens_list_professor),
    path('api/professor/mensagens/<int:conversa_id>', app.views.mensagem_conversa_detalhe_professor),
    path('api/coordenacao/notas/opcoes', app.views.opcoes_notas_coordenacao),
    path('api/coordenacao/notas/turma/<int:vinculo_id>', app.views.notas_turma_coordenacao),
    path('api/admin/login', app.views.admin_login),
    path('api/admin/auth', app.views.admin_auth),
    path('api/admin/escolas/opcoes', app.views.admin_escolas_opcoes),
    path('api/admin/coordenadores', app.views.admin_coordenadores),
    path('api/admin/coordenadores/<int:coordenador_id>', app.views.admin_coordenador_excluir),
    path('api/admin/professores', app.views.admin_professores),
    path('api/admin/professores/<int:professor_id>', app.views.admin_professor_excluir),
    path('api/admin/alunos', app.views.admin_alunos),
    path('api/admin/alunos/<int:aluno_id>', app.views.admin_aluno_excluir),
    path('api/admin/turmas', app.views.admin_turmas),
    path('api/admin/turmas/renomear', app.views.admin_turma_renomear),
    path('api/students/dashboard', app.views.dashboard_aluno),
    path('api/students/conteudos', app.views.conteudos_aluno),
    path('api/students/atividades', app.views.atividades_aluno),
    path('api/students/boletim', app.views.boletim_aluno),
    path('api/students/horarios', app.views.horarios_aluno),
    path('api/students/cronograma', app.views.cronograma_aluno),
    path('api/students/cronograma/<int:estudo_id>/concluir', app.views.cronograma_alternar_concluido),
    path('api/students/cronograma/<int:estudo_id>', app.views.cronograma_excluir),
    path('api/students/frequencia', app.views.frequencia_aluno),
    path('api/students/solicitacoes', app.views.solicitacoes_responsavel_aluno),
    path('api/students/solicitacoes/<int:vinculo_id>', app.views.solicitacao_responsavel_excluir),
    path('api/responsavel/registrar', app.views.registrar_responsavel),
    path('api/responsavel/login', app.views.login_responsavel),
    path('api/responsavel/auth', app.views.auth_responsavel),
    path('api/responsavel/vinculos', app.views.vinculos_responsavel),
    path('api/responsavel/vinculos/solicitar', app.views.solicitar_vinculo_responsavel),
    path('api/responsavel/alunos/buscar', app.views.buscar_alunos_para_responsavel),
    path('api/students/solicitacoes/<int:vinculo_id>/responder', app.views.solicitacao_responsavel_responder),
    path('api/responsavel/alunos/<int:aluno_id>/dashboard', app.views.dashboard_aluno_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/boletim', app.views.boletim_aluno_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/frequencia', app.views.frequencia_aluno_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/horario', app.views.horario_aluno_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/comunicados', app.views.comunicados_aluno_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/advertencias', app.views.advertencias_aluno_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/avaliacoes', app.views.avaliacoes_aluno_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/calendario', app.views.calendario_aluno_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/mensagem/professor/opcoes', app.views.opcoes_mensagem_professor_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/mensagem/professor', app.views.mensagens_professor_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/mensagem/professor/<int:conversa_id>', app.views.mensagem_conversa_professor_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/mensagem/coordenador/status', app.views.mensagem_coordenador_status_responsavel),
    path('api/responsavel/alunos/<int:aluno_id>/mensagem/coordenador/enviar', app.views.mensagem_coordenador_responsavel_enviar),
    path('api/responsavel/alunos/<int:aluno_id>/mensagem/coordenador/<int:conversa_id>', app.views.mensagem_conversa_coordenador_responsavel),
    path('api/professor/mensagens/responsaveis', app.views.mensagens_list_professor_responsaveis),
    path('api/professor/mensagens/responsaveis/<int:conversa_id>', app.views.mensagem_conversa_professor_responsavel_detalhe),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
