# Generated by Django 6.0.5 on 2026-05-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
    ]
