# Generated by Django 6.0.5 on 2026-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_address_user_full_name_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
