# Generated by Django 6.0.5 on 2026-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_user_cpf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudante",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("matricula", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=30, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("cpf", models.CharField(max_length=14, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("mom_name", models.CharField(max_length=300, null=True)),
                ("course", models.CharField(max_length=170, null=True)),
                ("ip", models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=30, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("cpf", models.CharField(max_length=14, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("mom_name", models.CharField(max_length=300, null=True)),
                ("materia", models.CharField(max_length=100, null=True)),
                ("ip", models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=30, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("cpf", models.CharField(max_length=14, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("student_full_name", models.CharField(max_length=300, null=True)),
                ("student_matricula", models.CharField(max_length=20, null=True)),
                ("ip", models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
