# Generated by Django 6.0.5 on 2026-06-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_estudante_professor_responsavel_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordenacao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=30, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("cpf", models.CharField(max_length=14, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("cargo", models.CharField(max_length=150, null=True)),
                ("ip", models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=300, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=30, null=True)),
                ("cpf", models.CharField(max_length=14, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="professor",
            name="mom_name",
        ),
        migrations.RemoveField(
            model_name="responsavel",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="responsavel",
            name="student_full_name",
        ),
        migrations.RemoveField(
            model_name="responsavel",
            name="student_matricula",
        ),
        migrations.AddField(
            model_name="professor",
            name="classes",
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name="professor",
            name="materia",
            field=models.CharField(max_length=700, null=True),
        ),
    ]
