# Generated by Django 6.0.5 on 2026-06-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_coordenacao_superadmin_remove_professor_mom_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordenacao",
            name="escola",
            field=models.CharField(max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="estudante",
            name="escola",
            field=models.CharField(max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="escola",
            field=models.CharField(max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="superadmin",
            name="escola",
            field=models.CharField(max_length=170, null=True),
        ),
    ]
