# Generated by Django 6.0.5 on 2026-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_coordenacao_escola_estudante_escola_professor_escola_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="superadmin",
            name="ip",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="superadmin",
            name="password",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
