# Generated by Django 6.0.5 on 2026-06-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_superadmin_ip_superadmin_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudante",
            name="address",
        ),
        migrations.RemoveField(
            model_name="estudante",
            name="course",
        ),
        migrations.RemoveField(
            model_name="estudante",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="estudante",
            name="email",
        ),
        migrations.RemoveField(
            model_name="estudante",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="estudante",
            name="ip",
        ),
        migrations.RemoveField(
            model_name="estudante",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="estudante",
            name="matricula",
        ),
        migrations.RemoveField(
            model_name="estudante",
            name="mom_name",
        ),
        migrations.RemoveField(
            model_name="estudante",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="estudante",
            name="curso",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="estudante",
            name="data_cadastro",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="estudante",
            name="modo_de_ensino",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="estudante",
            name="nome_completo",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="estudante",
            name="periodo",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="estudante",
            name="posicao_ordem",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="estudante",
            name="serie",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="estudante",
            name="turma",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="estudante",
            name="escola",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="estudante",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
