# Generated by Django 6.0.5 on 2026-06-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_estudante_address_remove_estudante_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudante",
            name="ip",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="estudante",
            name="senha",
            field=models.CharField(default="", null=True, verbose_name=300),
        ),
    ]
