# Generated by Django 6.0.5 on 2026-06-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_estudante_ip_estudante_senha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudante",
            name="ip",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
