# Generated by Django 6.0.5 on 2026-06-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_estudante_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudante",
            name="senha",
            field=models.CharField(default="12345678", null=True, verbose_name=300),
        ),
    ]
