# Generated by Django 6.0.6 on 2026-07-03 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_estudante_senha"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtravessaPor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escola", models.CharField(max_length=255, null=True)),
                ("turma", models.CharField(max_length=255, null=True)),
                ("etapa", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_disciplina", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SuperAdmin",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="address",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="classes",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="escola",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="ip",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="materia",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="professor",
            name="data_cadastro",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="nome_completo",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="professor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="atravessapor",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atravessamentos",
                to="app.professor",
            ),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="professores",
            field=models.ManyToManyField(
                related_name="disciplinas", to="app.professor"
            ),
        ),
    ]
