# Generated by Django 6.0.6 on 2026-07-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_atravessapor_disciplina_delete_superadmin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="senha",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
