# Generated by Django 6.0.6 on 2026-07-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_professor_senha"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="ip",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
