# Generated by Django 6.0.6 on 2026-07-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_professor_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="atravessapor",
            name="disciplina_lecionada",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
