# Generated by Django 6.0.7 on 2026-07-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_nota_delete_responsavel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coordenacao",
        ),
        migrations.AlterUniqueTogether(
            name="nota",
            unique_together={
                ("aluno", "disciplina", "turma", "professor", "ano_letivo")
            },
        ),
    ]
