# Generated by Django 6.0.7 on 2026-07-30 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_delete_coordenacao_alter_nota_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano_letivo", models.PositiveIntegerField(default=2026)),
                ("data", models.DateField()),
                ("presente", models.BooleanField(default=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="app.estudante",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="app.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias_registradas",
                        to="app.professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="app.atravessapor",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("aluno", "disciplina", "turma", "professor", "data")
                },
            },
        ),
    ]
