# Generated by Django 6.0.7 on 2026-07-31 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_frequencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano_letivo", models.PositiveIntegerField(default=2026)),
                ("data", models.DateField()),
                ("assunto", models.TextField(blank=True, default="")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="app.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas_ministradas",
                        to="app.professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="app.atravessapor",
                    ),
                ),
            ],
            options={
                "unique_together": {("disciplina", "turma", "professor", "data")},
            },
        ),
    ]
