# Generated by Django 6.0.7 on 2026-08-04 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_evento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conteudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano_letivo", models.PositiveIntegerField(default=2026)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, default="")),
                ("data", models.DateField()),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="conteudos/%Y/%m/"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conteudos",
                        to="app.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conteudos",
                        to="app.professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conteudos",
                        to="app.atravessapor",
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
    ]
