# Generated by Django 6.0.7 on 2026-08-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_comunicado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("senha", models.CharField(max_length=255)),
                ("escola", models.CharField(blank=True, default="", max_length=255)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
