# Generated by Django 6.0.7 on 2026-08-14 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_advertencia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="atualizado_em",
        ),
        migrations.AddField(
            model_name="evento",
            name="ano_letivo",
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name="evento",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos",
                to="app.professor",
            ),
        ),
    ]
