# Generated by Django 6.0.7 on 2026-08-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_remove_evento_atualizado_em_evento_ano_letivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="coordenador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_criados",
                to="app.coordenador",
            ),
        ),
    ]
