# Generated by Django 6.1 on 2026-08-19 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_evento_coordenador"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comunicado",
            options={},
        ),
        migrations.RemoveField(
            model_name="comunicado",
            name="criado_em",
        ),
        migrations.AddField(
            model_name="comunicado",
            name="coordenador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunicados",
                to="app.coordenador",
            ),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunicados",
                to="app.professor",
            ),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.atravessapor",
            ),
        ),
    ]
