# Generated by Django 6.1 on 2026-08-19 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_comunicado_options_remove_comunicado_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicado",
            name="data",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
