# Generated by Django 6.1 on 2026-08-20 01:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_alter_comunicado_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertencia",
            options={},
        ),
        migrations.RemoveField(
            model_name="advertencia",
            name="criado_em",
        ),
        migrations.AddField(
            model_name="advertencia",
            name="coordenador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertencias_emitidas",
                to="app.coordenador",
            ),
        ),
        migrations.AddField(
            model_name="advertencia",
            name="tipo",
            field=models.CharField(
                choices=[("ADVERTENCIA", "Advertência"), ("PENALIDADE", "Penalidade")],
                default="ADVERTENCIA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="advertencia",
            name="aluno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertencias",
                to="app.estudante",
            ),
        ),
        migrations.AlterField(
            model_name="advertencia",
            name="data",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="advertencia",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="advertencia",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertencias",
                to="app.professor",
            ),
        ),
    ]
