# Generated by Django 6.1 on 2026-08-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_alter_advertencia_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertencia",
            name="data_inicio_suspensao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advertencia",
            name="data_termino_suspensao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advertencia",
            name="is_suspensao",
            field=models.BooleanField(default=False),
        ),
    ]
