# Generated by Django 6.1 on 2026-08-20 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_advertencia_data_inicio_suspensao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorarioAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("SEG", "Segunda-feira"),
                            ("TER", "Terça-feira"),
                            ("QUA", "Quarta-feira"),
                            ("QUI", "Quinta-feira"),
                            ("SEX", "Sexta-feira"),
                        ],
                        max_length=3,
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="app.atravessapor",
                    ),
                ),
            ],
            options={
                "ordering": ["dia_semana", "hora_inicio"],
            },
        ),
    ]
