# Generated by Django 6.1 on 2026-08-30 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_horarioaula"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("senha", models.CharField(max_length=255)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("conteudo", models.TextField()),
                ("tempo_leitura", models.PositiveIntegerField(default=1)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="app.blogger",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_criacao"],
            },
        ),
    ]
