# Generated by Django 6.1 on 2026-08-30 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_blogger_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turma", models.CharField(max_length=100)),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data", models.DateField()),
                ("ano_letivo", models.IntegerField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.disciplina"
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="app.professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("enunciado", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("OBJETIVA", "Objetiva"), ("SUBJETIVA", "Subjetiva")],
                        default="OBJETIVA",
                        max_length=10,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="avaliacoes/questoes/"
                    ),
                ),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questoes",
                        to="app.avaliacao",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letra", models.CharField(max_length=1)),
                ("texto", models.CharField(max_length=300)),
                ("correta", models.BooleanField(default=False)),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternativas",
                        to="app.questao",
                    ),
                ),
            ],
            options={
                "ordering": ["letra"],
            },
        ),
    ]
