# Generated by Django 6.1 on 2026-09-01 16:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_avaliacao_questao_alternativa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alternativa",
            options={"ordering": ["ordem"]},
        ),
        migrations.AlterModelOptions(
            name="questao",
            options={"ordering": ["ordem"]},
        ),
        migrations.RemoveField(
            model_name="alternativa",
            name="correta",
        ),
        migrations.RemoveField(
            model_name="alternativa",
            name="letra",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="ano_letivo",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="disciplina",
        ),
        migrations.RemoveField(
            model_name="questao",
            name="imagem",
        ),
        migrations.AddField(
            model_name="alternativa",
            name="ordem",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="curso",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="alternativa",
            name="texto",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="data",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="titulo",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="app.atravessapor",
            ),
        ),
        migrations.AlterField(
            model_name="questao",
            name="tipo",
            field=models.CharField(
                choices=[("DISSERTATIVA", "Dissertativa"), ("OBJETIVA", "Objetiva")],
                max_length=20,
            ),
        ),
    ]
