# Generated by Django 6.1 on 2026-09-02 00:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_alter_alternativa_options_alter_questao_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alternativa",
            options={"ordering": ["letra"]},
        ),
        migrations.AlterModelOptions(
            name="questao",
            options={"ordering": ["ordem", "id"]},
        ),
        migrations.RemoveField(
            model_name="alternativa",
            name="ordem",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="curso",
        ),
        migrations.AddField(
            model_name="alternativa",
            name="correta",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alternativa",
            name="letra",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="ano_letivo",
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="disciplina",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.disciplina",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questao",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="avaliacoes/questoes/"
            ),
        ),
        migrations.AlterField(
            model_name="alternativa",
            name="texto",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="data",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="turma",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="questao",
            name="tipo",
            field=models.CharField(
                choices=[("OBJETIVA", "Objetiva"), ("SUBJETIVA", "Subjetiva")],
                default="OBJETIVA",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "coordenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas",
                        to="app.coordenador",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas",
                        to="app.professor",
                    ),
                ),
            ],
            options={
                "unique_together": {("professor", "coordenador")},
            },
        ),
        migrations.CreateModel(
            name="MensagemChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remetente_tipo",
                    models.CharField(
                        choices=[
                            ("PROFESSOR", "Professor"),
                            ("COORDENACAO", "Coordenação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("conteudo", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("lida_professor", models.BooleanField(default=False)),
                ("lida_coordenacao", models.BooleanField(default=False)),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="app.conversa",
                    ),
                ),
            ],
            options={
                "ordering": ["data_envio"],
            },
        ),
    ]
