# Generated by Django 6.1 on 2026-09-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_alter_alternativa_options_alter_questao_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("senha", models.CharField(max_length=255)),
                ("ip", models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
