# Generated by Django 6.1 on 2026-09-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstudoProgramado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("disciplina", models.CharField(blank=True, max_length=255)),
                ("data", models.DateField()),
                ("concluido", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudos_programados",
                        to="app.estudante",
                    ),
                ),
            ],
            options={
                "ordering": ["data"],
            },
        ),
    ]
