# Generated by Django 6.1 on 2026-09-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_estudoprogramado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("cpf", models.CharField(blank=True, default="", max_length=20)),
                ("telefone", models.CharField(blank=True, default="", max_length=30)),
                ("senha", models.CharField(blank=True, default="", max_length=255)),
                ("ip", models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
