# Generated by Django 6.1 on 2026-09-04 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_responsavel"),
    ]

    operations = [
        migrations.CreateModel(
            name="VinculoResponsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parentesco",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADO", "Aprovado"),
                            ("RECUSADO", "Recusado"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                ("data_resposta", models.DateTimeField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_responsavel",
                        to="app.estudante",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_aluno",
                        to="app.responsavel",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_solicitacao"],
                "unique_together": {("aluno", "responsavel")},
            },
        ),
    ]
