# Generated by Django 6.1 on 2026-09-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_vinculoresponsavel"),
    ]

    operations = [
        migrations.AddField(
            model_name="vinculoresponsavel",
            name="origem",
            field=models.CharField(
                choices=[
                    ("ALUNO", "Criado pelo aluno"),
                    ("RESPONSAVEL", "Solicitado pelo responsável"),
                ],
                default="ALUNO",
                max_length=15,
            ),
        ),
    ]
