# Generated by Django 6.1 on 2026-09-04 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_vinculoresponsavel_origem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversaResponsavelCoordenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas_responsavel_coordenador",
                        to="app.estudante",
                    ),
                ),
                (
                    "coordenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas_responsaveis",
                        to="app.coordenador",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas_coordenador",
                        to="app.responsavel",
                    ),
                ),
            ],
            options={
                "unique_together": {("responsavel", "coordenador", "aluno")},
            },
        ),
        migrations.CreateModel(
            name="ConversaResponsavelProfessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas_responsavel_professor",
                        to="app.estudante",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas_responsaveis",
                        to="app.professor",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas_professor",
                        to="app.responsavel",
                    ),
                ),
            ],
            options={
                "unique_together": {("responsavel", "professor", "aluno")},
            },
        ),
        migrations.CreateModel(
            name="MensagemChatResponsavelCoordenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remetente_tipo",
                    models.CharField(
                        choices=[
                            ("RESPONSAVEL", "Responsável"),
                            ("COORDENACAO", "Coordenação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("conteudo", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("lida_responsavel", models.BooleanField(default=False)),
                ("lida_coordenacao", models.BooleanField(default=False)),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="app.conversaresponsavelcoordenador",
                    ),
                ),
            ],
            options={
                "ordering": ["data_envio"],
            },
        ),
        migrations.CreateModel(
            name="MensagemChatResponsavelProfessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remetente_tipo",
                    models.CharField(
                        choices=[
                            ("RESPONSAVEL", "Responsável"),
                            ("PROFESSOR", "Professor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("conteudo", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("lida_responsavel", models.BooleanField(default=False)),
                ("lida_professor", models.BooleanField(default=False)),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="app.conversaresponsavelprofessor",
                    ),
                ),
            ],
            options={
                "ordering": ["data_envio"],
            },
        ),
    ]
