# Generated by Django 6.1 on 2026-09-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_conversaresponsavelcoordenador_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessaoBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ALUNO", "Aluno"),
                            ("PROFESSOR", "Professor"),
                            ("RESPONSAVEL", "Responsável"),
                            ("COORDENADOR", "Coordenador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("referencia_id", models.PositiveIntegerField()),
                ("nome_completo", models.CharField(max_length=255)),
                ("ip", models.CharField(max_length=45, unique=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="autor",
        ),
        migrations.AddField(
            model_name="post",
            name="autor_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="autor_nome",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="autor_tipo",
            field=models.CharField(
                choices=[
                    ("ALUNO", "Aluno"),
                    ("PROFESSOR", "Professor"),
                    ("RESPONSAVEL", "Responsável"),
                    ("COORDENADOR", "Coordenador"),
                ],
                default="ALUNO",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autor_tipo",
                    models.CharField(
                        choices=[
                            ("ALUNO", "Aluno"),
                            ("PROFESSOR", "Professor"),
                            ("RESPONSAVEL", "Responsável"),
                            ("COORDENADOR", "Coordenador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("autor_id", models.PositiveIntegerField()),
                ("autor_nome", models.CharField(max_length=255)),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="app.post",
                    ),
                ),
            ],
            options={
                "ordering": ["data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Curtida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autor_tipo",
                    models.CharField(
                        choices=[
                            ("ALUNO", "Aluno"),
                            ("PROFESSOR", "Professor"),
                            ("RESPONSAVEL", "Responsável"),
                            ("COORDENADOR", "Coordenador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("autor_id", models.PositiveIntegerField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curtidas",
                        to="app.post",
                    ),
                ),
            ],
            options={
                "unique_together": {("post", "autor_tipo", "autor_id")},
            },
        ),
    ]
