# Generated by Django 6.1 on 2026-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_sessaoblog_remove_post_autor_post_autor_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/posts/%Y/%m/"
            ),
        ),
    ]
