# Generated by Django 6.1 on 2026-09-14 11:48

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_post_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sessao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ALUNO", "Aluno"),
                            ("PROFESSOR", "Professor"),
                            ("RESPONSAVEL", "Responsável"),
                            ("COORDENADOR", "Coordenador"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("referencia_id", models.PositiveIntegerField()),
                ("nome_completo", models.CharField(max_length=255)),
                (
                    "token",
                    models.CharField(
                        default=app.models.gerar_token_sessao,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SessaoBlog",
        ),
        migrations.AlterField(
            model_name="comentario",
            name="autor_tipo",
            field=models.CharField(
                choices=[
                    ("ALUNO", "Aluno"),
                    ("PROFESSOR", "Professor"),
                    ("RESPONSAVEL", "Responsável"),
                    ("COORDENADOR", "Coordenador"),
                    ("ADMIN", "Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="curtida",
            name="autor_tipo",
            field=models.CharField(
                choices=[
                    ("ALUNO", "Aluno"),
                    ("PROFESSOR", "Professor"),
                    ("RESPONSAVEL", "Responsável"),
                    ("COORDENADOR", "Coordenador"),
                    ("ADMIN", "Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="autor_tipo",
            field=models.CharField(
                choices=[
                    ("ALUNO", "Aluno"),
                    ("PROFESSOR", "Professor"),
                    ("RESPONSAVEL", "Responsável"),
                    ("COORDENADOR", "Coordenador"),
                    ("ADMIN", "Admin"),
                ],
                default="ALUNO",
                max_length=20,
            ),
        ),
    ]
