# Generated by Django 6.1 on 2026-09-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_sessao_delete_sessaoblog_alter_comentario_autor_tipo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ALUNO", "Aluno"),
                            ("PROFESSOR", "Professor"),
                            ("RESPONSAVEL", "Responsável"),
                            ("COORDENADOR", "Coordenador"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("referencia_id", models.PositiveIntegerField()),
                ("nome_usuario", models.CharField(max_length=30, unique=True)),
                ("bio", models.TextField(blank=True, default="")),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                (
                    "status_relacionamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOLTEIRO", "Solteiro(a)"),
                            ("NAMORANDO", "Namorando"),
                            ("CASADO", "Casado(a)"),
                            ("COMPLICADO", "É complicado"),
                            ("NAO_INFORMAR", "Prefiro não informar"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/perfis/%Y/%m/"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("tipo", "referencia_id")},
            },
        ),
    ]
